BuddhaNexus/buddhanexus

api/db_queries.py, api/main.py
This is a PR in conjunction with a PR in the frontend. It is just an attempt to add a filter so if you could give some comments on how I can improve that please do so so I can learn from doing these things.
=> [140] update filter to filter for files and collections

api/db_queries.py, api/models_api.py, dataloader/models_dataloader.py
Just a small error in the filtering.
=> [n/a] correcting error for co-occurances

api/main.py
This may fix your CORS issues @ayya-vimala . The last lines in this PR are just unrelated formatting changes.
=> [n/a] add cors wildcard

api/db_queries.py, api/main.py, api/utils.py, dataloader/loader.py, dataloader/utils.py
This in conjunction with the frontend PR. I could not figure a good way of sorting the collections properly in the backend so I have sent it to the frontend to sort there. Maybe not the best way so have a look and discard the PR if you think it can be done better.
=> [171] sorted header number view

api/main.py
=> [n/a] small update to key display in graphs view

api/db_queries.py, api/main.py
@sebastian-nehrdich - one solution to the case-insensitive search
=> 205-update search with case-insensitive

api/db_queries.py
Tiny change to remove english from tibetan names for visual chart
=> [N/A] remove english translation from tibetan names for visual chart

api/db_queries.py, api/main.py, dataloader/loader.py, dataloader/utils.py
This are some updates for the backend to make it work with the 205-branch on the frontend. Please be aware that the development branch of the frontend will not work with this.
=> Fast queries

.travis.yml, Makefile, api/db_actions.py, api/db_connection.py, api/db_queries.py, api/main.py, api/models_api.py, api/utils.py, dataloader/__init__.py, dataloader/utils.py, docker-compose.prod.yml, docker-compose.yml, setup/Dockerfile-dataloader, setup/Dockerfile-fastapi
This is still work in progress.
- Adds travis and pylint to the API sub-project
- The dataloader project still needs pylint fixes
- We should test the page with this branch before merging
=> [216] add simple travis script

api/main.py
Just removing the parallel count data that is no longer used.
=> removing parallel count from numbers view

data/tib-files.json
I change the display of the Tibetan texts to display the Derge numbers only in the combo-box.
=> [N/A] change display tibetan

api/db_queries.py, api/main.py, dataloader/loader.py, dataloader/utils.py
This fixes the right-side display for pali and chinese.
=> Fix pali loading

api/db_queries.py, dataloader/loader.py
I refactored it a bit and removed a bug. But please check it for the Tibetan with a larger dataset. It might take a long time to load.
=> Visual loading cleaned

Makefile, dataloader/tasks.py
Just something to clean the totals collections before any new load because otherwise they get a key error and do not load the data.
=> cleaning totals collections

api/db_queries.py, api/main.py, dataloader/loader.py
This is the code to load all the visual data into the backend without filtering for all 3 layers.
=> 3 layer visual

api/main.py
Fixing the bug in the counting for the histogram
=> [4] add filecount to histogram

dataloader/loader.py
Just removing the zeros of the third layer in visual
=> remove zeros from single entries

api/db_queries.py, api/main.py
Adding a query for the sidebar menu.
=> Menu query

.env.example, api/main.py, api/utils.py
While fixing 73 it automatically also fixed 71. It was the batchsize for the numbersview that was the problem.
=> bugs 71 and 73 loading problems in numbes view

api/db_queries.py, api/main.py, api/models_api.py
This is for a small bug on the frontend that Orna discovered.
=> Small fixes to the text-view that solve a bug of the middle-view.

dataloader/dataloader_utils.py
I think it can be simple as this!
=> 67 grabh db load local

api/main.py, api/utils.py, data/skt-categories.json, data/skt-collections.json, data/skt-files.json, data/tib-collections.json, dataloader/loader.py
Some fixes to Sanskrit data and to collection regex patterns in order to make Sanskrit data work.
Black also made some style changes.
=> 93 Sanskrit collections added

data/chn-collections.json, data/pli-collections.json
new load is needed after this is merged.
So: `make load-menu-data` and `make clean-totals`
=> 91 correcting bug in visual loading subcollections

api/utils.py
Small bug that prevented certain Pali and Chinese collections to load in the filters.
=> 97 filters bug for collections with dash

.env.example, api/utils.py
=> 105 add filters for sanskrit

dataloader/dataloader_utils.py, dataloader/tasks.py, dataloader/tasks_menu.py
This are just two small fixes for problems that I encountered when loading larger datasets.
=> Small fixes to make partial data-loading easier.

api/main.py, api/queries/main_queries.py, api/queries/search_queries.py, api/search/search_utils.py, dataloader/tasks_segments_parallels.py
This are some performance tweaks for the search function.
=> Search function improvements

api/utils.py
I think this will solve the numbers view because this function did not return the right collections and now it does (tested in local testfile). I can however not make it work on local backend so not sure if there are more issues. In any case, this function should be changed.
=> 142 numbers view

api/queries/search_queries.py, api/search/search_utils.py, dataloader/views_properties.py
Some small changes to speedup the TIbetan search function.
=> Fix to speed up the tibetan search engine.

data/tib-categories.json
Some changes to the tibetan category names as requested by Orna.
=> Changes to the Tibetan data sets.

api/queries/main_queries.py
Small fix for an issue of the table view.
=> Small fix that solves problems with the table view.

dataloader/dataloader_utils.py, dataloader/tasks_segments_parallels.py
This fixes the kind-of-broken sorting of the hit texts.
=> Small fix for the sorting of the hit texts.

dataloader/tasks_segments_parallels.py
Folios only need to be loaded for certain files. For others it can give errors while loading.
=> 205 folios only loaded for certain files

api/queries/main_queries.py
This will return the textname (acronym) together with the DisplayName so it can be used in the frontend to display instead of the filename.
=> Display textname

data/pli-categories.json, data/pli-files.json
Making the m dot consistent with the new pali data from Sujato
=> changing m dot for pali data

data/skt-collections.json
New sanskrit collections to take out the diacritics and also the collections that do not exist.
=> changes to Sanskrit collections without diacritics

dataloader/dataloader_constants.py, dataloader/tasks_segments_parallels.py
Part 2 of the fix for visuals: the collection pattern for loading did not include some collections.
=> 251 categories loading for visuals

api/main.py
This builds in a check that if not all files are loaded it falls back to the filenumber again otherwise it crashes.
=> 270 return full names for histogram

api/main.py
small fix to make the chinese histogram work correctly.
=> Fix chinese graph

api/main.py, dataloader/dataloader_utils.py, dataloader/tasks_segments_parallels.py
This load the folios for sanskrit and pali. For sanskrit and pali commentaries it uses every 10th segment number except for a few files where it loads something more meaningful. For other pali it loads pts section numbers.
=> 278 loading segment nrs

api/main.py, api/queries/main_queries.py, api/utils.py, data/skt-categories.json, data/skt-files.json
This adds folio selection to table view on the backend
Also changed Sanskrit category names
Numbers view is not done until numbers view is changed from graph database.
=> 153 add folio selection to table view

api/main.py, api/queries/main_queries.py, api/queries/menu_queries.py, dataloader/tasks_multilingual.py
This adds functionality for a new menupoint for the multilingual files.
=> Multilang new menu

api/main.py
Returning multilingual data for the sidebar.
=> 312 querying menu data for multilingual sidebar

data/chn-files.json
important change to the filenames in CHN.
=> Changed Chinese filenames

Makefile, dataloader/tasks.py
I added this in order to have the option to load ai separate from english data to speed up the process.
=> loading ai separate from english

api/main.py, api/queries/main_queries.py, api/search/search_utils.py, api/table_download.py, api/utils.py, dataloader/dataloader_utils.py, dataloader/tasks_segments_parallels.py, docker-compose.yml
this is a new PR for the fixing of the regexes, the previous branch had some unintended changes. 
We should aim at getting rid of all the uses of regex on the backend queries, they reduce speed and also the readability of the code is not that good. I am not sure whether these changes work well for Pali, I tested for Sanskit, Tibetan and Chinese so far.
=> Imported from previous branch

api/main.py, api/search/search_utils.py
this creates the necessary functionality to filter search results based on collections. 
It works via the limit_collection parameter that is passed to the search api request. 
It is then tested whether a segment_nr of a search result begins with any of the entries in limit_collection, it should therefore work with collections, categories and even files. 
While this is returning the right data, it is not working properly with the search function because the frontend is not updating correctly.
=> Advanced search

data/pli-categories.json, data/pli-collections.json, data/pli-files.json
I've changed the structure of the Pali commentaries to have a more logical and readable layout. I have not actually tested it on my system as I'm having some technical problems at the moment so I hope it doesn't break anything when loading. If it does, let me know!
=> New pali structure

api/colormaps.py
As per issue #131 - abbreviating long matches with an ellipsis. Not sure if this is wanted but it was easy to make.
=> abbreviating long matches with an ellipsis

.gitignore, api/links.py, api/queries/main_queries.py, api/utils.py
Removing some small errors that prevented loading of certain items.
I also made a change to the text-view API
=> removing link error VRI + limit collection regex error

api/endpoints/models/table_view_models.py, api/table_download.py
=> using bytesIO for download

api/queries/menu_queries.py
The menu data is not in the right order. I've added a SORT to the query to make sure that doesn't happen but it will add extra time to the calculations. There might be another way?
=> Sorting menu data

api/endpoints/download.py, api/endpoints/numbers_view.py, api/links.py
I noticed the API gave back wrong links data for Pali so I corrected that but also made some corrections to the other ones. If no link is mentioned in the links data filed then it will return false for all, BUT ... did we actually want  any other links? I noticed you also uploaded the bdrc links for some of the tibetan files. So please have a look and update the file as needed. 
(black also made a few changes to other files but nothing big)
=> correcting link data

api/endpoints/numbers_view.py
Small error, big consequences! Just making the numbers view default folio into a string.
=> numbers view folio error removed

frontend/src/components/layout/Footer.tsx
This is just a very small padding change for the footer menu as I didn't like the padding ... it looked a bit wrong to me.
Please delete this PR if you don't agree!
=> change padding static page menu footer

api/queries/graph_view_queries.py, frontend/prod.Dockerfile
See issue #353 
`FOR current_parallel IN SLICE(target_file.parallels_randomized, 0, 2500)` only works for larger datasets. If the first 2500 matches in the randomized dataset are mostly filtered out and the result is only two items, the result is not correct.
Limiting it to 2500 matches AFTER filtering is better.
=> 353 graph view error

frontend/src/features/globalSearch/GlobalSearchStyledMuiComponents.tsx, frontend/src/features/tableView/ParallelSegment.tsx, frontend/src/features/tableView/TableViewRow.tsx
- fix text view parallel sement width
- #365 fix dark global search bar bg colour
=> hotfix display bugs

api/download.py, api/endpoints/download.py, api/endpoints/numbers_view.py, api/queries/numbers_view_queries.py, api/queries/table_view_queries.py
- Fixed not working pagination in numbers view
- Fixed folio retrieval when first folio is not 0
- Fixed numbers view download not accepting folios and giving back wrong results
=> fix sn and an files not working in numbers view and pagination

api/endpoints/search.py, api/queries/search_query_builder.py, api/search/search_utils.py
Fixes wonky behavior of the search function; be aware this is an ongoing process and we likely still have problems ahead.
=> Search fixes
